### ISSUE TITLE
Peer:to:Peer code review

### ISSUE THREAD

**Issue by rammazzoti2000** [rammazzoti2000/Advanced-Building-Blocks---Enumerables#7]
morning session code review March 25th

**Comment by adamclasic** [comment]
Your project looks are good no issues.

**Comment by Kyle-Law** [comment]
Hi @rammazzoti2000 , `[nil].my_none?` should return true but got `false` for in your case. Apart from that, everything looks fine 👍

**Comment by dili021** [comment]
Good job and welcome to the storks!

**Comment by nyatindopatrick** [comment]
Clean code. Good work!

**Comment by patriciachrysy** [comment]
Good job so far Alex but your enumerables are not working for hashes, all of them. For example when I do `{one:1, two:2, three:3,four:4}.my_selesct{|key, value| value.even?}` I should get `{two:2, four:4}` but I am getting an error.
Also agree with @Kyle-Law 
Apart from that, good job

**Comment by rammazzoti2000** [comment]
Hey @patriciachrysy thank you for your feedback, the methods given by Microverse to build are supposed to work with arrays only. I can see in ruby docs that the each_with_index is the only one supposed to also accept a hash, but was not required by Microverse.
I agree with @Kyle-Law as well

**Comment by patriciachrysy** [comment]
@rammazzoti2000, maybe it's true, dunno. Maybe I'll check again. saying this because I saw that those functions must work just like the original does and the originals work with both arrays, hashes, and ranges, even each_with_index, you can check that. Some even got the remak fron TSE to make it work with hashes and ranges too(all of them).
